### ISSUE TITLE
Cross-device link

### ISSUE THREAD

**Issue by mahmoud** [manuelRiel/upodder#8]
Hey there! Thanks for picking up maintenance of upodder! 

I ran into a problem when using upodder from PyPI. If your /tmp/ directory is on a different partition than your target directory (as is very common with *nix machines), you'll see an error like this:

```
(snip)
python2.7/site-packages/upodder/upodder.py", line 127, in _download_enclosure
    os.rename(downloadto, moveto)
OSError: [Errno 18] Cross-device link
```

Moves/renames can't be executed across partitions/devices like that. The usual response is to either:

  1. *Copy* the target to destination, then delete the original copy of the target.
  2. Use a location on the same partition as the temporary file.

The latter is preferable in most of my experience, so I created the AtomicSaver ([docs](http://boltons.readthedocs.org/en/latest/fileutils.html#atomic-file-saving), [code](https://github.com/mahmoud/boltons/blob/master/boltons/fileutils.py#L185)). Give it a glance and let me know if you'd like any help fixing this issue.

**Comment by manuelRiel** [comment]
Hi Mahmoud. This is a valid issue. Thanks for binging it to my attention. Using a real `move`-function instead of rename should solve this. I'll let you know when a new build is available on pypi.

**Comment by manuelRiel** [comment]
Sorry it took so long. @gaspar0069 fixed it when adding more support for file extensions.
